export const dummyGasMeterListData = [
  {
    key: 1,
    id: 1,
    name: 'gas flow meter 1',
    applicationCategory: 'gas_flow_meter',
    applicationType: 1,
    volumetricFlow: '7.9 SCM/hr',
    massFlow: '8.2 m3/hr',
    temperature: { value: '447.4', unit: 'celsius' },
    meterStatus: 'ON',
    children: [
      {
        key: 1,
        id: 1,
        name: 'sub gas flow meter 1',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '15.5 kg/hr',
        massFlow: '4.1 kg/hr',
        temperature: { value: '104.3', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 2,
        id: 2,
        name: 'sub gas flow meter 2',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '14.6 kg/hr',
        massFlow: '2.0 kg/hr',
        temperature: { value: '453.0', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 3,
        id: 3,
        name: 'sub gas flow meter 3',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '9.0 kg/hr',
        massFlow: '5.1 kg/hr',
        temperature: { value: '233.1', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 4,
        id: 4,
        name: 'sub gas flow meter 4',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '10.9 kg/hr',
        massFlow: '4.7 kg/hr',
        temperature: { value: '256.9', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 5,
        id: 5,
        name: 'sub gas flow meter 5',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '9.9 kg/hr',
        massFlow: '4.6 kg/hr',
        temperature: { value: '433.9', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 6,
        id: 6,
        name: 'sub gas flow meter 6',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '16.5 kg/hr',
        massFlow: '8.6 kg/hr',
        temperature: { value: '378.0', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 7,
        id: 7,
        name: 'sub gas flow meter 7',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '14.8 kg/hr',
        massFlow: '5.5 kg/hr',
        temperature: { value: '484.4', unit: 'celsius' },
        meterStatus: 'ON',
      },
    ],
  },
  {
    key: 2,
    id: 2,
    name: 'gas flow meter 2',
    applicationCategory: 'gas_flow_meter',
    applicationType: 1,
    volumetricFlow: '18.8 kg/hr',
    massFlow: '5.5 kg/hr',
    temperature: { value: '138.2', unit: 'celsius' },
    meterStatus: 'ON',
    children: [
      {
        key: 8,
        id: 8,
        name: 'sub gas flow meter 8',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '11.9 kg/hr',
        massFlow: '1.2 kg/hr',
        temperature: { value: '179.0', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 9,
        id: 9,
        name: 'sub gas flow meter 9',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '17.4 kg/hr',
        massFlow: '7.8 kg/hr',
        temperature: { value: '380.7', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 10,
        id: 10,
        name: 'sub gas flow meter 10',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '18.9 kg/hr',
        massFlow: '9.4 kg/hr',
        temperature: { value: '182.5', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 11,
        id: 11,
        name: 'sub gas flow meter 11',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '10.7 kg/hr',
        massFlow: '5.2 kg/hr',
        temperature: { value: '228.1', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 12,
        id: 12,
        name: 'sub gas flow meter 12',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '18.4 kg/hr',
        massFlow: '9.7 kg/hr',
        temperature: { value: '119.3', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 13,
        id: 13,
        name: 'sub gas flow meter 13',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '5.6 kg/hr',
        massFlow: '2.5 kg/hr',
        temperature: { value: '353.0', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 14,
        id: 14,
        name: 'sub gas flow meter 14',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '10.6 kg/hr',
        massFlow: '1.3 kg/hr',
        temperature: { value: '490.3', unit: 'celsius' },
        meterStatus: 'ON',
      },
    ],
  },
  {
    key: 3,
    id: 3,
    name: 'gas flow meter 3',
    applicationCategory: 'gas_flow_meter',
    applicationType: 1,
    volumetricFlow: '19.9 kg/hr',
    massFlow: '2.6 kg/hr',
    temperature: { value: '262.7', unit: 'celsius' },
    meterStatus: 'ON',
    children: [
      {
        key: 15,
        id: 15,
        name: 'sub gas flow meter 15',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '10.8 kg/hr',
        massFlow: '5.7 kg/hr',
        temperature: { value: '470.4', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 16,
        id: 16,
        name: 'sub gas flow meter 16',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '10.4 kg/hr',
        massFlow: '0.6 kg/hr',
        temperature: { value: '428.9', unit: 'celsius' },
        meterStatus: 'OFF',
      },
      {
        key: 17,
        id: 17,
        name: 'sub gas flow meter 17',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '9.8 kg/hr',
        massFlow: '2.1 kg/hr',
        temperature: { value: '416.2', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 18,
        id: 18,
        name: 'sub gas flow meter 18',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '5.9 kg/hr',
        massFlow: '9.2 kg/hr',
        temperature: { value: '38.7', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 19,
        id: 19,
        name: 'sub gas flow meter 19',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '18.5 kg/hr',
        massFlow: '8.0 kg/hr',
        temperature: { value: '431.7', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 20,
        id: 20,
        name: 'sub gas flow meter 20',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '14.8 kg/hr',
        massFlow: '4.4 kg/hr',
        temperature: { value: '325.7', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 21,
        id: 21,
        name: 'sub gas flow meter 21',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '17.9 kg/hr',
        massFlow: '9.4 kg/hr',
        temperature: { value: '369.9', unit: 'celsius' },
        meterStatus: 'ON',
      },
    ],
  },
  {
    key: 4,
    id: 4,
    name: 'gas flow meter 4',
    applicationCategory: 'gas_flow_meter',
    applicationType: 1,
    volumetricFlow: '18.7 kg/hr',
    massFlow: '5.4 kg/hr',
    temperature: { value: '78.9', unit: 'celsius' },
    meterStatus: 'ON',
    children: [
      {
        key: 22,
        id: 22,
        name: 'sub gas flow meter 22',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '14.8 kg/hr',
        massFlow: '8.6 kg/hr',
        temperature: { value: '21.5', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 23,
        id: 23,
        name: 'sub gas flow meter 23',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '13.0 kg/hr',
        massFlow: '9.5 kg/hr',
        temperature: { value: '299.6', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 24,
        id: 24,
        name: 'sub gas flow meter 24',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '20.0 kg/hr',
        massFlow: '5.3 kg/hr',
        temperature: { value: '138.9', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 25,
        id: 25,
        name: 'sub gas flow meter 25',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '14.2 kg/hr',
        massFlow: '4.5 kg/hr',
        temperature: { value: '227.0', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 26,
        id: 26,
        name: 'sub gas flow meter 26',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '8.6 kg/hr',
        massFlow: '0.5 kg/hr',
        temperature: { value: '109.2', unit: 'celsius' },
        meterStatus: 'OFF',
      },
      {
        key: 27,
        id: 27,
        name: 'sub gas flow meter 27',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '19.3 kg/hr',
        massFlow: '7.1 kg/hr',
        temperature: { value: '154.6', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 28,
        id: 28,
        name: 'sub gas flow meter 28',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '12.7 kg/hr',
        massFlow: '9.8 kg/hr',
        temperature: { value: '13.6', unit: 'celsius' },
        meterStatus: 'ON',
      },
    ],
  },
  {
    key: 5,
    id: 5,
    name: 'gas flow meter 5',
    applicationCategory: 'gas_flow_meter',
    applicationType: 1,
    volumetricFlow: '6.9 kg/hr',
    massFlow: '3.5 kg/hr',
    temperature: { value: '494.3', unit: 'celsius' },
    meterStatus: 'ON',
    children: [
      {
        key: 29,
        id: 29,
        name: 'sub gas flow meter 29',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '19.6 kg/hr',
        massFlow: '0.4 kg/hr',
        temperature: { value: '385.0', unit: 'celsius' },
        meterStatus: 'OFF',
      },
      {
        key: 30,
        id: 30,
        name: 'sub gas flow meter 30',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '5.8 kg/hr',
        massFlow: '7.4 kg/hr',
        temperature: { value: '437.9', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 31,
        id: 31,
        name: 'sub gas flow meter 31',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '18.7 kg/hr',
        massFlow: '2.1 kg/hr',
        temperature: { value: '489.9', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 32,
        id: 32,
        name: 'sub gas flow meter 32',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '5.7 kg/hr',
        massFlow: '8.1 kg/hr',
        temperature: { value: '213.8', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 33,
        id: 33,
        name: 'sub gas flow meter 33',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '14.2 kg/hr',
        massFlow: '0.8 kg/hr',
        temperature: { value: '243.9', unit: 'celsius' },
        meterStatus: 'OFF',
      },
      {
        key: 34,
        id: 34,
        name: 'sub gas flow meter 34',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '18.0 kg/hr',
        massFlow: '2.1 kg/hr',
        temperature: { value: '462.4', unit: 'celsius' },
        meterStatus: 'ON',
      },
      {
        key: 35,
        id: 35,
        name: 'sub gas flow meter 35',
        applicationCategory: 'sub_gas_flow_meter',
        applicationType: 1,
        volumetricFlow: '5.4 kg/hr',
        massFlow: '7.6 kg/hr',
        temperature: { value: '347.4', unit: 'celsius' },
        meterStatus: 'ON',
      },
    ],
  },
];

export function gasMeterListTransformer(resp) {
  if (!resp) {
    return [];
  }
  return resp.results.map((item) => {
    const childGasMeterData = item.sub_gas_flow_meter.map((subGasMeter) => {
      return {
        key: subGasMeter.id,
        id: subGasMeter.id,
        name: subGasMeter.name,
        applicationCategory:
          subGasMeter.application_details.application_category,
        applicationType: subGasMeter.gas_meter_type,
        volumetricFlow: `${subGasMeter.sub_gas_flow_meter_reading.volumetric_flow.value.toFixed(
          1,
        )} ${subGasMeter.sub_gas_flow_meter_reading.volumetric_flow.unit}`,
        massFlow: `${subGasMeter.sub_gas_flow_meter_reading.mass_flow.value.toFixed(
          1,
        )} ${subGasMeter.sub_gas_flow_meter_reading.mass_flow.unit}`,
        temperature: {
          value: `${subGasMeter.sub_gas_flow_meter_reading.temperature.value.toFixed(
            1,
          )}`,
          unit: `${subGasMeter.sub_gas_flow_meter_reading.temperature.unit}`,
        },
        meterStatus: subGasMeter.sub_gas_flow_meter_reading.meter_status,
      };
    });
    return {
      key: item.id,
      id: item.id,
      name: item.name,
      applicationCategory: item.application_details.application_category,
      applicationType: item.gas_meter_type,
      volumetricFlow: `${item.gas_flow_meter_reading.volumetric_flow.value.toFixed(
        1,
      )} ${item.gas_flow_meter_reading.volumetric_flow.unit}`,
      massFlow: `${item.gas_flow_meter_reading.mass_flow.value.toFixed(1)} ${
        item.gas_flow_meter_reading.mass_flow.unit
      }`,
      temperature: {
        value: `${item.gas_flow_meter_reading.temperature.value.toFixed(1)}`,
        unit: `${item.gas_flow_meter_reading.temperature.unit}`,
      },
      meterStatus: item.gas_flow_meter_reading.meter_status,
      children: childGasMeterData,
    };
  });
}
