export const dummyPlantPerformanceData = {
  productionAvailability: true,
  plantStartDate: '2021-02-14',
  firstBlock: [
    { key: 1, name: 'Specific Energy Consumption', value: '0 kWh/tonnes' },
    { key: 2, name: 'Specific Energy Cost', value: '1 ₹/tonnes' },
    { key: 3, name: 'Total Energy Consumption', value: '6 kWh' },
    { key: 4, name: 'Specific Emission', value: '0.00 tCO2/tonnes' },
    { key: 5, name: 'Plant Load Factor', value: '0.02 %' },
    { key: 6, name: 'Production', value: '51' },
  ],
  secondBlock: [
    { key: 1, name: 'Energy in TOE', value: '0.001' },
    { key: 2, name: 'GHG Emission', value: '0.00 tCO2' },
  ],
  graphData: [
    { timestamp: '10', xAxisParam: 5.5, yAxisParam: 1443.034287 },
    { timestamp: '11', xAxisParam: 5.761, yAxisParam: 2530.694465 },
    { timestamp: '12', xAxisParam: 4.557, yAxisParam: 1319.171056 },
  ],
  energyConsumptionSummary: [
    {
      key: 'Sub Meter 1 Default',
      meterName: 'Sub Meter 1 Default',
      energyConsumption: '1.03',
      percentageShare: '17.48',
    },
    {
      key: 'Sub Meter 2 DG',
      meterName: 'Sub Meter 2 DG',
      energyConsumption: '0.99',
      percentageShare: '16.85',
    },
    {
      key: 'Sub Meter 3 Solar',
      meterName: 'Sub Meter 3 Solar',
      energyConsumption: '1.02',
      percentageShare: '17.31',
    },
    {
      key: 'sub meter 4 Air Compressor',
      meterName: 'sub meter 4 Air Compressor',
      energyConsumption: '0.95',
      percentageShare: '16.10',
    },
    {
      key: 'sub meter 5',
      meterName: 'sub meter 5',
      energyConsumption: '0.98',
      percentageShare: '16.71',
    },
    {
      key: 'sub meter 6',
      meterName: 'sub meter 6',
      energyConsumption: '1.02',
      percentageShare: '17.34',
    },
    {
      key: 'sub meter 7',
      meterName: 'sub meter 7',
      energyConsumption: '0.93',
      percentageShare: '15.74',
    },
    {
      key: 'sub meter 8',
      meterName: 'sub meter 8',
      energyConsumption: '0.97',
      percentageShare: '16.56',
    },
    {
      key: 'sub meter 9',
      meterName: 'sub meter 9',
      energyConsumption: '1.01',
      percentageShare: '17.20',
    },
    {
      key: 'sub meter 10',
      meterName: 'sub meter 10',
      energyConsumption: '1.00',
      percentageShare: '16.97',
    },
    {
      key: 'sub meter 11',
      meterName: 'sub meter 11',
      energyConsumption: '1.01',
      percentageShare: '17.20',
    },
    {
      key: 'sub meter 12',
      meterName: 'sub meter 12',
      energyConsumption: '1.02',
      percentageShare: '17.31',
    },
    {
      key: 'sub meter 13',
      meterName: 'sub meter 13',
      energyConsumption: '1.00',
      percentageShare: '17.02',
    },
    {
      key: 'sub meter 14',
      meterName: 'sub meter 14',
      energyConsumption: '1.00',
      percentageShare: '17.02',
    },
    {
      key: 'sub meter 15',
      meterName: 'sub meter 15',
      energyConsumption: '0.97',
      percentageShare: '16.44',
    },
    {
      key: 'sub meter 16',
      meterName: 'sub meter 16',
      energyConsumption: '1.01',
      percentageShare: '17.14',
    },
    {
      key: 'sub meter 17',
      meterName: 'sub meter 17',
      energyConsumption: '1.02',
      percentageShare: '17.27',
    },
    {
      key: 'sub meter 18',
      meterName: 'sub meter 18',
      energyConsumption: '1.03',
      percentageShare: '17.49',
    },
    {
      key: 'sub meter 19',
      meterName: 'sub meter 19',
      energyConsumption: '0.98',
      percentageShare: '16.66',
    },
    {
      key: 'sub meter 20',
      meterName: 'sub meter 20',
      energyConsumption: '0.98',
      percentageShare: '16.66',
    },
    {
      key: 'sub meter 21',
      meterName: 'sub meter 21',
      energyConsumption: '1.02',
      percentageShare: '17.37',
    },
    {
      key: 'sub meter 22',
      meterName: 'sub meter 22',
      energyConsumption: '0.98',
      percentageShare: '16.63',
    },
    {
      key: 'sub meter 23',
      meterName: 'sub meter 23',
      energyConsumption: '1.02',
      percentageShare: '17.26',
    },
    {
      key: 'sub meter 24',
      meterName: 'sub meter 24',
      energyConsumption: '1.00',
      percentageShare: '17.05',
    },
    {
      key: 'sub meter 25',
      meterName: 'sub meter 25',
      energyConsumption: '0.98',
      percentageShare: '16.61',
    },
    {
      key: 'sub meter 26',
      meterName: 'sub meter 26',
      energyConsumption: '1.00',
      percentageShare: '16.92',
    },
    {
      key: 'sub meter 27',
      meterName: 'sub meter 27',
      energyConsumption: '0.98',
      percentageShare: '16.58',
    },
    {
      key: 'sub meter 28',
      meterName: 'sub meter 28',
      energyConsumption: '1.01',
      percentageShare: '17.20',
    },
    {
      key: 'sub meter 29',
      meterName: 'sub meter 29',
      energyConsumption: '1.01',
      percentageShare: '17.24',
    },
    {
      key: 'sub meter 30',
      meterName: 'sub meter 30',
      energyConsumption: '1.03',
      percentageShare: '17.44',
    },
    {
      key: 'sub meter 31',
      meterName: 'sub meter 31',
      energyConsumption: '1.03',
      percentageShare: '17.54',
    },
    {
      key: 'sub meter 32',
      meterName: 'sub meter 32',
      energyConsumption: '0.99',
      percentageShare: '16.75',
    },
    {
      key: 'sub meter 33',
      meterName: 'sub meter 33',
      energyConsumption: '0.97',
      percentageShare: '16.47',
    },
    {
      key: 'sub meter 34',
      meterName: 'sub meter 34',
      energyConsumption: '0.98',
      percentageShare: '16.69',
    },
    {
      key: 'sub meter 35',
      meterName: 'sub meter 35',
      energyConsumption: '0.98',
      percentageShare: '16.64',
    },
    {
      key: 'others',
      meterName: 'others',
      energyConsumption: '-29.02',
      percentageShare: '-492.87',
    },
  ],
  firstTable: [
    { key: 1, name: 'Current Harmonics', value: '134.76 %' },
    { key: 2, name: 'Voltage Harmonics', value: '139.21 %' },
    { key: 3, name: 'Average PF', value: '0.99' },
  ],
  secondTable: [
    { key: 1, name: 'PF(Lead/Lag)', value: 'MAX = 0.99' },
    { key: 2, name: '', value: 'MIN = -0.99' },
    { key: 3, name: '', value: 'AVG = -0.02' },
  ],
};
