// application type 7 is for water meter dummy data
export const response = [
  {
    key: 1,
    id: 1,
    name: 'Water Meter 1',
    details: 'details Water meter',
    applicationType: 7,
    applicationCategory: 'water_meter',
    percentageLoading: '149.3 %',
    powerFactor: '0.617',
    currentTotal: '68.50',
    meterStatus: 'ON',
    children: [
      {
        key: 1,
        id: 1,
        name: 'Sub Water Meter 1',
        details:
          'Keep the type and name the same. Do not change the type or the name',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '149.3 %',
        powerFactor: '0.096',
        currentTotal: '10.81',
        meterStatus: 'OFF',
      },
      {
        key: 4,
        id: 4,
        name: 'Sub Water Meter 4 ',
        details: 'details Water meter',
        applicationType: 5,
        applicationCategory: 'sub_meter',
        percentageLoading: '164.8 %',
        powerFactor: '0.148',
        currentTotal: '13.69',
        meterStatus: 'OFF',
      },
      {
        key: 5,
        id: 5,
        name: 'Sub Water Meter 5',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '149.9 %',
        powerFactor: '0.785',
        currentTotal: '44.59',
        meterStatus: 'ON',
      },
      {
        key: 6,
        id: 6,
        name: 'Sub Water Meter 6',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '113.3 %',
        powerFactor: '0.994',
        currentTotal: '61.06',
        meterStatus: 'OFF',
      },
      {
        key: 7,
        id: 7,
        name: 'Sub Water Meter 7',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '166.0 %',
        powerFactor: '-0.977',
        currentTotal: '93.43',
        meterStatus: 'OFF',
      },
    ],
  },
  {
    key: 2,
    id: 2,
    name: 'Water meter 2',
    details: 'details Water meter',
    applicationType: 7,
    applicationCategory: 'water_meter',
    percentageLoading: '0.0 %',
    powerFactor: '-0.829',
    currentTotal: '17.38',
    meterStatus: 'OFF',
    children: [
      {
        key: 8,
        id: 8,
        name: 'Sub Water Meter 8',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '160.6 %',
        powerFactor: '0.943',
        currentTotal: '38.97',
        meterStatus: 'OFF',
      },
      {
        key: 9,
        id: 9,
        name: 'Sub Water Meter 9',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '140.6 %',
        powerFactor: '-0.356',
        currentTotal: '5.95',
        meterStatus: 'OFF',
      },
      {
        key: 10,
        id: 10,
        name: 'Sub Water Meter 10',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '119.2 %',
        powerFactor: '0.733',
        currentTotal: '-1.46',
        meterStatus: 'OFF',
      },
      {
        key: 11,
        id: 11,
        name: 'Sub Water Meter 11',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '115.3 %',
        powerFactor: '-0.268',
        currentTotal: '-9.38',
        meterStatus: 'OFF',
      },
      {
        key: 12,
        id: 12,
        name: 'Sub Water Meter 12',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '116.1 %',
        powerFactor: '0.461',
        currentTotal: '33.05',
        meterStatus: 'OFF',
      },
      {
        key: 13,
        id: 13,
        name: 'Sub Water Meter 13',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '165.5 %',
        powerFactor: '0.094',
        currentTotal: '-2.54',
        meterStatus: 'OFF',
      },
      {
        key: 14,
        id: 14,
        name: 'Sub Water Meter 14',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '121.9 %',
        powerFactor: '-0.226',
        currentTotal: '66.94',
        meterStatus: 'OFF',
      },
    ],
  },
  {
    key: 3,
    id: 3,
    name: 'Water meter 3',
    details: 'details Water meter',
    applicationType: 7,
    applicationCategory: 'water_meter',
    percentageLoading: '137.8 %',
    powerFactor: '-0.102',
    currentTotal: '35.28',
    meterStatus: 'ON',
    children: [
      {
        key: 15,
        id: 15,
        name: 'Sub Water Meter 15',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '133.6 %',
        powerFactor: '-0.280',
        currentTotal: '72.39',
        meterStatus: 'OFF',
      },
      {
        key: 16,
        id: 16,
        name: 'Sub Water Meter 16',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '133.6 %',
        powerFactor: '-0.398',
        currentTotal: '96.77',
        meterStatus: 'OFF',
      },
      {
        key: 17,
        id: 17,
        name: 'Sub Water Meter 17',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '160.3 %',
        powerFactor: '-0.315',
        currentTotal: '76.96',
        meterStatus: 'OFF',
      },
      {
        key: 18,
        id: 18,
        name: 'Sub Water Meter 18',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '163.4 %',
        powerFactor: '-0.659',
        currentTotal: '62.11',
        meterStatus: 'OFF',
      },
      {
        key: 19,
        id: 19,
        name: 'Sub Water Meter 19',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '155.0 %',
        powerFactor: '-0.676',
        currentTotal: '43.65',
        meterStatus: 'OFF',
      },
      {
        key: 20,
        id: 20,
        name: 'Sub Water Meter 20',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '128.6 %',
        powerFactor: '-0.153',
        currentTotal: '2.89',
        meterStatus: 'OFF',
      },
      {
        key: 21,
        id: 21,
        name: 'Sub Water Meter 21',
        details: 'details Water meter',
        applicationType: 1,
        applicationCategory: 'sub_meter',
        percentageLoading: '165.4 %',
        powerFactor: '-0.822',
        currentTotal: '27.24',
        meterStatus: 'OFF',
      },
    ],
  },
];
